services:
#######################
# Opensource-instans    #
#######################
  opensource:
    build: .
    ports:
      - "8000:80"
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - "C:/Program Files/MariaDB 12.0/cert/ca-cert.pem:/var/www/html/storage/sql-ca.pem:ro"
      - ./.env:/var/www/html/.env:ro
      - ./storage:/var/www/html/storage
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          ignore:
            - node_modules/
            - vendor/
            - storage/
            - .git
        - action: rebuild
          path: package.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
